### ISSUE TITLE
Deprecation warning in Django 1.8

### ISSUE THREAD

**Issue by SalahAdDin** [digi604/django-smart-selects#79]
Now, we have the next warning:

```
/home/tulipan/Proyectos/TiempoTurco/lib/python3.4/site-packages/smart_selects/views.py:10: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
  model_class = get_model(app, model)
```

Can anyone fix it?

**Comment by jimmykobe1171** [comment]
fixed on new release 1.1.1

**Comment by jamiecounsell** [comment]
This still seems to be an issue for Django 1.9:

```
(procurement)MacBook-Pro:app jamiecounsell$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jamiecounsell/Projects/procurement/app/configuration/models.py", line 11, in <module>
    from smart_selects.db_fields import ChainedForeignKey
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/smart_selects/db_fields.py", line 11, in <module>
    from smart_selects import form_fields
  File "/Users/jamiecounsell/.virtualenvs/procurement/lib/python2.7/site-packages/smart_selects/form_fields.py", line 1, in <module>
    from django.db.models import get_model
```

**Comment by SalahAdDin** [comment]
:+1:

**Comment by jimmykobe1171** [comment]
New version 1.2.0 has been released and it includes this fix :)
